#!/bin/bash
CURPATH="$(pwd -P)"
    YEAR=$(date +'%Y')
    INCREMENT_FILENAME=${CURPATH}/resources/music2program2
    TEMPLATE=${CURPATH}/bin/templates/music2program2.md
    NUMBER=$(cat "$INCREMENT_FILENAME")
    TEMPLATE=$(cat "$TEMPLATE")
    INCREMENTED_NUMBER=$((NUMBER + 1))
    echo "${INCREMENTED_NUMBER}" >"${INCREMENT_FILENAME}"
    #hugo new --kind music2program2 blog/"${YEAR}"/music-to-program-to-"${INCREMENTED_NUMBER}"
    mkdir -p ./content/blog/"${YEAR}"/music-to-program-to-"${INCREMENTED_NUMBER}"/
    echo eval "${TEMPLATE}" >./content/blog/"${YEAR}"/music-to-program-to-"${INCREMENTED_NUMBER}"/index.md
    code ./content/blog/"${YEAR}"/music-to-program-to-"${INCREMENTED_NUMBER}"/index.md
