#!/bin/bash
CURPATH="$(pwd -P)"
    YEAR=$(date +'%Y')
    read -r -p 'Month: ' TAG
    hugo new --kind notes-from-the-laboratory blog/"${YEAR}"/notes-from-the-laboratory-"${MONTH}"
    code ./content/blog/"${YEAR}"/notes-from-the-laboratory-"${MONTH}"/index.md
