#!/bin/bash
CURPATH="$(pwd -P)"
    YEAR=$(date +'%Y')
    # MONTH=$(date +'%B')
    read -r -p 'Title: ' POST
    POST=${POST// /-}
    POST=${POST,,}
    hugo new blog/"${YEAR}"/"${POST}"
    code ./content/blog/"${YEAR}"/"${POST}"/index.md
